

export default class Constants {
  /**
   * label font weight 400.
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * title font weight 500.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * course item padding 12.
   */
  static readonly COURSE_ITEM_PADDING: number = 12;

  /**
   * loading duration 2000.
   */
  static readonly LOADING_DURATION: number = 2000;

  /**
   * title line number 2.
   */
  static readonly TITLE_LINE_NUMBER: number = 2;

  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * classify title percent.
   */
  static readonly CLASSIFY_TITLE_PERCENT: string = '55%';



  /**
   * Font weight.
   */
  static readonly FONT_WEIGHT: number = 500;


  /**
   * Recent text height.
   */
  static readonly RECENT_TEXT_HEIGHT: string = '2.7%';

  /**
   * Recent text width.
   */
  static readonly RECENT_TEXT_WIDTH: string = '48.9%';

  /**
   * Delete image height.
   */
  static readonly DELETE_IMAGE_HEIGHT: string = '3.1%';

  /**
   * Delete image width.
   */
  static readonly DELETE_IMAGE_WIDTH: string = '6.7%';

  /**
   * No search image height.
   */
  static readonly NO_SEARCH_IMAGE_HEIGHT: string = '15.4%';

  /**
   * No search image width.
   */
  static readonly NO_SEARCH_IMAGE_WIDTH: string = '33.3%';

  /**
   * No search text height.
   */
  static readonly NO_SEARCH_TEXT_HEIGHT: string = '2.7%';

  /**
   * No search text width.
   */
  static readonly NO_SEARCH_TEXT_WIDTH: string = '26.7%';

  /**
   * Flew layout padding top.
   */
  static readonly FLEX_PADDING_TOP: string = '0.8%';

  /**
   * Flew layout padding bottom.
   */
  static readonly FLEX_PADDING_BOTTOM: string = '0.8%';

  /**
   * Flew layout padding left.
   */
  static readonly FLEX_PADDING_LEFT: string = '4.4%';

  /**
   * Flew layout padding right.
   */
  static readonly FLEX_PADDING_RIGHT: string = '4.4%';

  /**
   * Search input height.
   */
  static readonly SEARCH_HEIGHT: string = '5.1%';

  /**
   * Search input width.
   */
  static readonly SEARCH_WIDTH: string = '81.1%';

  /**
   * Text max line.
   */
  static readonly TEXT_MAX_LINE: number = 2;

  /**
   * Search placeholder.
   */
  static readonly SEARCH_PLACEHOLDER: string = '搜索...';

  /**
   * Layout weight.
   */
  static readonly LAYOUT_WEIGHT: number = 8;

  /**
   * Search icon.
   */
  static readonly SEARCH_ICON: string = '/resources/base/media/ic_search.png';

}

